/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package sabah;

/**
 *
 * @author yazan
 */

import java.sql.*;

public class DatabaseOperation {
    
    //file path where netbeans is going to find the access
    //Connection String to establish a connection to the Access database
    private static final String url = "jdbc:ucanaccess://C://Users//yazan//Documents//NetBeansProjects//LeaveManagementSystem//DB.accdb";
    
    //to connect the database
    private Connection conn;
    //to run query
    private PreparedStatement statement; //Sequel code placed
    //to get data from the table
    private ResultSet resultSet;
    
     
    //Constructor to connect the database
     public DatabaseOperation()
    {
       try // connecting to the database
         {
            conn = DriverManager.getConnection(url); //try to connect the Driver Manger to connect to the url
         }
       catch(SQLException e)
        {
           System.out.println("Cannot connect database");
        }
    }
    
    
    //Execute query and return resultSet object after running the query
    //Enter an SQL Statement to be executed 
    //Output - table of data representing results generated by executing the statement
    public ResultSet query(String stmt) throws SQLException
    {
     statement = conn.prepareStatement(stmt);
     resultSet = statement.executeQuery();
     return resultSet;
    }
    
    //Input SQL Statemnt as a String 
    //Statement will be executed - Example (INSERT into a database or DELETE from a database)
    public void update(String update) throws SQLException
    {
     statement = conn.prepareStatement(update);
     statement.execute();
     statement.close();
    }
            
    //Converts ResultSet object into a String seperated by "" to deliminate
    //input: rs Parameter - ResultSet generated by the query
    //output: return data converted into a string each on a new line
    public String proccessResultSet(ResultSet rs)
    {
       String temp = "";
       try
        {
             ResultSetMetaData meta = rs.getMetaData();
             int size = meta.getColumnCount();
      
            while (rs.next())
             {
                for (int x = 1; x <= size; x++)
                   {
                      Object value = rs.getObject(x);
                      temp = temp + "" + value + "\t";
                   }
                
                temp = temp + "\n";
             }
         }
       catch(SQLException e)
        {
            e.printStackTrace();
        }
       
     return temp;
    }
     
            
    
    
}
