/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sabah;

import java.awt.Color;
import java.time.LocalDate;
import java.sql.*;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author yazan
 */
public class EditEmployeeUI extends javax.swing.JFrame {

    /**
     * Creates new form EditEmployeeUI
     */
    
    LeaveManagementManager lM;
    
    public EditEmployeeUI() {
        initComponents();
        
        try
        {
         lM = new LeaveManagementManager();
        }
        catch (SQLException e)
        {
            System.out.println("Can not create lM");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmployee = new javax.swing.JLabel();
        lblFirstname = new javax.swing.JLabel();
        lblSurname = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblJobTitle = new javax.swing.JLabel();
        lblTypeOfEmployment = new javax.swing.JLabel();
        lblEmploymentDate = new javax.swing.JLabel();
        lblEmploymentStatus = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txfFirstname = new javax.swing.JTextField();
        txfSurname = new javax.swing.JTextField();
        cmbGender = new javax.swing.JComboBox<>();
        txfJobTitle = new javax.swing.JTextField();
        dtpEmploymentDate = new com.github.lgooddatepicker.components.DatePicker();
        cmbEmploymentStatus = new javax.swing.JComboBox<>();
        txfUsername = new javax.swing.JTextField();
        txfPassword = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblErrorFirstname = new javax.swing.JLabel();
        lblErrorSurname = new javax.swing.JLabel();
        lblErrorGender = new javax.swing.JLabel();
        lblErrorJobTitle = new javax.swing.JLabel();
        lblErrorTypeOfEmployment = new javax.swing.JLabel();
        lblErrorEmploymentDate = new javax.swing.JLabel();
        lblErrorEmploymentStatus = new javax.swing.JLabel();
        lblErrorUsername = new javax.swing.JLabel();
        lblErrorPassword = new javax.swing.JLabel();
        cmbTypeOfEmployment = new javax.swing.JComboBox<>();
        lblContactDetails = new javax.swing.JLabel();
        txfContactDetails = new javax.swing.JTextField();
        lblErrorContactDetails = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEmployee.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        lblEmployee.setText("Employee (General User)");

        lblFirstname.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblFirstname.setText("Firstname:");

        lblSurname.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblSurname.setText("Surname:");

        lblGender.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblGender.setText("Gender:");

        lblJobTitle.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblJobTitle.setText("Job Title:");

        lblTypeOfEmployment.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblTypeOfEmployment.setText("Type of Employment:");

        lblEmploymentDate.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblEmploymentDate.setText("Employment Date:");

        lblEmploymentStatus.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblEmploymentStatus.setText("Employment Status:");

        lblUsername.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblUsername.setText("Username:");

        lblPassword.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblPassword.setText("Password:");

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        cmbEmploymentStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        cmbTypeOfEmployment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Permanent", "Part-Time" }));

        lblContactDetails.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblContactDetails.setText("Contact Details: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTypeOfEmployment)
                                    .addGap(30, 30, 30)
                                    .addComponent(cmbTypeOfEmployment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblJobTitle)
                                    .addGap(109, 109, 109)
                                    .addComponent(txfJobTitle))
                                .addComponent(lblEmployee)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblEmploymentDate)
                                    .addGap(46, 46, 46)
                                    .addComponent(dtpEmploymentDate, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblFirstname)
                                        .addComponent(lblSurname)
                                        .addComponent(lblGender))
                                    .addGap(99, 99, 99)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txfSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                        .addComponent(txfFirstname)
                                        .addComponent(cmbGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEmploymentStatus)
                                        .addComponent(lblUsername)
                                        .addComponent(lblPassword))
                                    .addGap(37, 37, 37)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txfPassword)
                                        .addComponent(cmbEmploymentStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txfUsername)
                                        .addComponent(txfContactDetails))))
                            .addComponent(lblContactDetails))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                .addComponent(btnBack)
                                .addContainerGap(124, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblErrorSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(lblErrorFirstname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblErrorGender, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(lblErrorJobTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(lblErrorTypeOfEmployment, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(lblErrorEmploymentDate, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(lblErrorEmploymentStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(lblErrorUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(lblErrorPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(lblErrorContactDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployee)
                    .addComponent(btnBack))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstname)
                    .addComponent(txfFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorFirstname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSurname)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txfSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblErrorSurname)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGender)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblErrorGender)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJobTitle)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txfJobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblErrorJobTitle)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTypeOfEmployment)
                        .addComponent(cmbTypeOfEmployment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblErrorTypeOfEmployment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmploymentDate)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dtpEmploymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblErrorEmploymentDate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmploymentStatus)
                    .addComponent(cmbEmploymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorEmploymentStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername)
                    .addComponent(txfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassword)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblErrorPassword)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContactDetails)
                    .addComponent(txfContactDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorContactDetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        EmployeesUI e = new EmployeesUI();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        String employeeName = "";
        String employeeSurname = "";
        String employeeGender = "";
        String employeeJobTitle = "";
        String typeOfEmployment = "";
        LocalDate employmentDate = null;
        String Status = "";
        String username = "";
        String password = "";
        int contactDetails;
        String contactDetailsToString = "";
        
        if (txfFirstname.getText().length() < 1)
        {
         lblErrorFirstname.setText("Firstname Required");
         txfFirstname.setBackground(Color.red);
        }
        else if (txfFirstname.getText().length() > 1)
        {
         lblErrorFirstname.setText("");
         txfFirstname.setBackground(Color.white);
         employeeName = txfFirstname.getText();
        }
        
        if (txfSurname.getText().length() < 1)
        {
         lblErrorSurname.setText("Surname Required");
         txfSurname.setBackground(Color.red);
        }
        else if (txfSurname.getText().length() > 1)
        {
         lblErrorSurname.setText("");
         txfSurname.setBackground(Color.white);
         employeeSurname = txfSurname.getText();
        }
        
        switch (cmbGender.getSelectedIndex())
        {
            case 0: employeeGender = "Male";
            break;
            case 1: employeeGender = "Female";
            break;
        }
        
        if (txfJobTitle.getText().length() < 1)
        {
         lblErrorJobTitle.setText("Job Title Required");
         txfJobTitle.setBackground(Color.red);
        }
        else if (txfJobTitle.getText().length() > 1)
        {
         lblErrorJobTitle.setText("");
         txfJobTitle.setBackground(Color.white);
         employeeJobTitle = txfJobTitle.getText();
        }
        
        switch (cmbTypeOfEmployment.getSelectedIndex())
        {
            case 0: typeOfEmployment = "Permanent";
            break;
            case 1: typeOfEmployment = "Part-Time";
        }
        
        if (dtpEmploymentDate.getText().length() < 1)
        {
         lblErrorEmploymentDate.setText("Date Required");
         dtpEmploymentDate.setBackground(Color.red);
        }
        else if (dtpEmploymentDate.getText().length() > 1)
        {
        employmentDate = LocalDate.parse(dtpEmploymentDate.getText(), DateTimeFormatter.ofPattern("dd MMMM yyyy"));
        lblErrorEmploymentDate.setText("");
        dtpEmploymentDate.setBackground(Color.white);
        }
        
        
        switch(cmbTypeOfEmployment.getSelectedIndex())
        {
            case 0: Status = "Active";
            break;
            case 1: Status = "Inactive";
        }
        
        if (txfUsername.getText().length() < 1)
        {
         lblErrorUsername.setText("Username Require");
         txfUsername.setBackground(Color.red);
        }
        else if (txfUsername.getText().length() > 1)
        {
         lblErrorUsername.setText("");
         txfUsername.setBackground(Color.white);
         username = txfUsername.getText();
        }
        
         if (txfPassword.getText().length() < 1)
        {
         lblErrorPassword.setText("Username Require");
         txfPassword.setBackground(Color.red);
        }
        else if (txfPassword.getText().length() > 1)
        {
         lblErrorPassword.setText("");
         txfPassword.setBackground(Color.white);
         password = txfPassword.getText();
        }
         
         
          if (txfContactDetails.getText().length() < 1)
        {
         txfContactDetails.setBackground(Color.red);
         lblErrorContactDetails.setText("Contact Details Required");
        }
        else if (txfContactDetails.getText().length() < 10 || txfContactDetails.getText().length() > 10)
        {
         txfContactDetails.setBackground(Color.red);
         lblErrorContactDetails.setText("Contact Details Must Be 10 Digits");
        }
        else if (txfContactDetails.getText().length() == 10)
        {
            try
            {
             contactDetails = Integer.parseInt(txfContactDetails.getText());
             contactDetailsToString = "" + contactDetails;
             lblErrorContactDetails.setText("");
             txfContactDetails.setBackground(Color.white);
            }
            catch (NumberFormatException e)
            {
             txfContactDetails.setBackground(Color.red);
             lblErrorContactDetails.setText("Digits Required");
            }
        }

     
        
        
         try
         {
          LoginUI.db.update("INSERT INTO Employees (Name, Surname, Gender, JobTitle, TypeOfEmployment, EmploymentDate, Status, Username, Password, ContactDetails) "
                  + "VALUES ('" + employeeName + "','" + employeeSurname + "','" + employeeGender + "','" + employeeJobTitle + "','" + typeOfEmployment +
                  "','" + employmentDate + "','" + Status + "','" + username + "','" + password + "','" + contactDetailsToString + "');)");
          
          lM.addEmployee(employeeName, employeeSurname, employeeGender, employeeJobTitle, typeOfEmployment, employmentDate, Status, username, password, contactDetailsToString);
         }
         catch(SQLException e)
         {
             System.out.println(e);
         }
       
     
     

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        /*if (txfUsername.getText().length() > 1 && txfPassword.getText().length() > 1)
        {
         try
         {
          LoginUI.db.update("DELETE FROM Employees WHERE Username = '" + txfUsername.getText() + "' AND Password = '" + txfPassword.getText() + "';)");
         }
         catch (SQLException e)
         {
             System.out.println(e);
         }
        }*/
    }//GEN-LAST:event_btnDeleteActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEmployeeUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbEmploymentStatus;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JComboBox<String> cmbTypeOfEmployment;
    private com.github.lgooddatepicker.components.DatePicker dtpEmploymentDate;
    private javax.swing.JLabel lblContactDetails;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JLabel lblEmploymentDate;
    private javax.swing.JLabel lblEmploymentStatus;
    private javax.swing.JLabel lblErrorContactDetails;
    private javax.swing.JLabel lblErrorEmploymentDate;
    private javax.swing.JLabel lblErrorEmploymentStatus;
    private javax.swing.JLabel lblErrorFirstname;
    private javax.swing.JLabel lblErrorGender;
    private javax.swing.JLabel lblErrorJobTitle;
    private javax.swing.JLabel lblErrorPassword;
    private javax.swing.JLabel lblErrorSurname;
    private javax.swing.JLabel lblErrorTypeOfEmployment;
    private javax.swing.JLabel lblErrorUsername;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblJobTitle;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblTypeOfEmployment;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txfContactDetails;
    private javax.swing.JTextField txfFirstname;
    private javax.swing.JTextField txfJobTitle;
    private javax.swing.JTextField txfPassword;
    private javax.swing.JTextField txfSurname;
    private javax.swing.JTextField txfUsername;
    // End of variables declaration//GEN-END:variables
}
