/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sabah;

import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author yazan
 */
public class EditUserUI extends javax.swing.JFrame {

    /**
     * Creates new form EditUserUI
     */
    LeaveManagementManager lM;
    
    public EditUserUI() {
        initComponents();
        
        
        try
        {
         lM = new LeaveManagementManager();
        }
        catch (SQLException e)
        {
            System.out.println("Cant create Users Array");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdminUser = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblSurname = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblFirstname = new javax.swing.JLabel();
        lblContactDetails = new javax.swing.JLabel();
        txfSurname = new javax.swing.JTextField();
        txfFirstname = new javax.swing.JTextField();
        txfContactDetails = new javax.swing.JTextField();
        txfUsername = new javax.swing.JTextField();
        txfPassword = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblErrorFirstname = new javax.swing.JLabel();
        lblErrorUsername = new javax.swing.JLabel();
        lblErrorSurname = new javax.swing.JLabel();
        lblErrorContactDetails = new javax.swing.JLabel();
        lblErrorPassword = new javax.swing.JLabel();
        lblNote = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAdminUser.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        lblAdminUser.setText("Admin User");

        lblPassword.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblPassword.setText("Password:");

        lblSurname.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblSurname.setText("Surname:");

        lblUsername.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblUsername.setText("Username:");

        lblFirstname.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblFirstname.setText("Firstname:");

        lblContactDetails.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblContactDetails.setText("Contact Details:");

        txfSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfSurnameActionPerformed(evt);
            }
        });

        txfContactDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfContactDetailsActionPerformed(evt);
            }
        });

        txfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfUsernameActionPerformed(evt);
            }
        });

        txfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfPasswordActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblNote.setFont(new java.awt.Font("Segoe UI Emoji", 3, 14)); // NOI18N
        lblNote.setText("To Delete: Only Username and Password Required");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSurname)
                            .addComponent(lblUsername)
                            .addComponent(lblAdminUser)
                            .addComponent(lblPassword)
                            .addComponent(lblContactDetails)
                            .addComponent(lblFirstname))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBack)
                                .addGap(25, 25, 25))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txfSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblErrorSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txfFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblErrorFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(181, 181, 181)
                                        .addComponent(lblErrorUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txfContactDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblErrorContactDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblErrorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNote, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblAdminUser)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFirstname)
                            .addComponent(txfFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorFirstname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSurname)
                            .addComponent(txfSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorSurname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsername)
                            .addComponent(txfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorUsername)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContactDetails)
                    .addComponent(txfContactDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorContactDetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNote)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfSurnameActionPerformed

    private void txfContactDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfContactDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfContactDetailsActionPerformed

    private void txfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfUsernameActionPerformed

    private void txfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfPasswordActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        UsersUI uI = new UsersUI();
        uI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        String firstName = "";
        String surname = "";
        String username = "";
        int contactDetails;
        String contactDetailsToStringFormat = "";
        String password = "";
        
        if (txfFirstname.getText().length() < 1)
        {
         txfFirstname.setBackground(Color.red);
         lblErrorFirstname.setText("Firstname Required");
        }
        else if (txfFirstname.getText().length() > 1)
        {
         firstName = txfFirstname.getText();
         txfFirstname.setBackground(Color.white);
         lblErrorFirstname.setText("");
        }
        
     
        if (txfSurname.getText().length() < 1)
        {
         txfSurname.setBackground(Color.red);
         lblErrorSurname.setText("Surname Required");
        }
       
        else if (txfSurname.getText().length() > 1)
        {
         surname = txfSurname.getText();
         txfSurname.setBackground(Color.white);
         lblErrorSurname.setText("");
        }
        
        
        if (txfUsername.getText().length() < 1)
        {
         txfUsername.setBackground(Color.red);
         lblErrorUsername.setText("Username Required");
        }
        else if (txfUsername.getText().length() > 1)
        {
         username = txfUsername.getText();
         txfUsername.setBackground(Color.white);
         lblErrorUsername.setText("");
        }
        
        
        
        if (txfContactDetails.getText().length() < 1)
        {
         txfContactDetails.setBackground(Color.red);
         lblErrorContactDetails.setText("Contact Details Required");
        }
        else if (txfContactDetails.getText().length() < 10 || txfContactDetails.getText().length() > 10)
        {
         txfContactDetails.setBackground(Color.red);
         lblErrorContactDetails.setText("Contact Details Must Be 10 Digits");
        }
        else if (txfContactDetails.getText().length() == 10)
        {
            try
            {
             contactDetails = Integer.parseInt(txfContactDetails.getText());
             contactDetailsToStringFormat = "" + contactDetails;
             lblErrorContactDetails.setText("");
             txfContactDetails.setBackground(Color.white);
            }
            catch (NumberFormatException e)
            {
             txfContactDetails.setBackground(Color.red);
             lblErrorContactDetails.setText("Digits Required");
            }
        }
        
        
        
        if (txfPassword.getText().length() < 1)
        {
         txfPassword.setBackground(Color.red);
         lblErrorPassword.setText("Password Required");
        }
        else if (txfPassword.getText().length() > 1)
        {
         password = txfPassword.getText();
         txfPassword.setBackground(Color.white);
         lblErrorPassword.setText("");
        }
        
        
        
     if ((txfContactDetails.getText().length() == 10 && contactDetailsToStringFormat.length() > 1) && txfSurname.getText().length() > 1 && txfFirstname.getText().length() > 1 && txfUsername.getText().length() > 1 &&
             txfPassword.getText().length() > 1)
      {
          
          try
              {
                  LoginUI.db.update("INSERT INTO AdminUsers (Name, Surname, usernameEmail, contactDetails, password)" + 
                 "VALUES ('" + firstName + "','" + surname + "','" + username + "','" + contactDetailsToStringFormat + "','" + password + "');");
                   lM.addUser(firstName, surname, username, contactDetailsToStringFormat, password);
                   JOptionPane.showMessageDialog(null, "Added to Database");
                  
                
              }
           catch(SQLException e)
              {
                 System.out.println("Could Not Add To Database");
              }
          
          
      
      }
     
     
     
     
    
        
     
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        
        if (txfFirstname.getText().length() > 1)
        { 
            lblErrorFirstname.setText("Leave Field Empty");
            txfFirstname.setBackground(Color.red);
        }
        
        if (txfSurname.getText().length() > 1)
        {
         lblErrorSurname.setText("Leave Field Empty");
         txfSurname.setBackground(Color.red);
        }
        
        if (txfContactDetails.getText().length() > 1)
        {
         lblErrorContactDetails.setText("Leave Field Empty");
         txfContactDetails.setBackground(Color.red);
        }
        
        if (txfUsername.getText().length() < 1)
        {
         lblErrorUsername.setText("Username Required");
         txfUsername.setBackground(Color.red);
        }
        else if (txfUsername.getText().length() > 1)
        {
         lblErrorUsername.setText("");
         txfUsername.setBackground(Color.white);
        }
        
        if (txfPassword.getText().length() < 1)
        {
         lblErrorPassword.setText("Username Required");
         txfPassword.setBackground(Color.red);
        }
        else if (txfPassword.getText().length() > 1)
        {
         lblErrorPassword.setText("");
         txfPassword.setBackground(Color.white);
        }
        
        
        
        
        
        if (txfPassword.getText().length() > 1 && txfUsername.getText().length() > 1 && txfContactDetails.getText().length() < 1 && txfFirstname.getText().length() < 1
                && txfSurname.getText().length() < 1)
        {
         try
         {
          LoginUI.db.update("DELETE FROM AdminUsers WHERE usernameEmail = '" + txfUsername.getText() + "','" + " AND password = '" + txfPassword.getText() + "';");
          JOptionPane.showMessageDialog(null, "Deleted from database");
         }
         catch (SQLException e)
         {
             System.out.println("Can not delete from database \n" + e);
         }
        }
       
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditUserUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblAdminUser;
    private javax.swing.JLabel lblContactDetails;
    private javax.swing.JLabel lblErrorContactDetails;
    private javax.swing.JLabel lblErrorFirstname;
    private javax.swing.JLabel lblErrorPassword;
    private javax.swing.JLabel lblErrorSurname;
    private javax.swing.JLabel lblErrorUsername;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txfContactDetails;
    private javax.swing.JTextField txfFirstname;
    private javax.swing.JTextField txfPassword;
    private javax.swing.JTextField txfSurname;
    private javax.swing.JTextField txfUsername;
    // End of variables declaration//GEN-END:variables
}
